### ISSUE TITLE
Pretrans & Posttrans sections not highlighted correctly

### ISSUE THREAD

**Issue by Keyhaku** [waveclaw/language-rpm-spec#11]
Hello,

It seems %pretrans & posttrans sections are not correctly handled, the "trans" part is not colored.

See ya.

![incorrecthighlight](https://cloud.githubusercontent.com/assets/8914368/17076664/51964a5a-50b8-11e6-8f00-66849937979d.jpg)

**Comment by waveclaw** [comment]
I will have to cut a new release to support this.

There is documentation on the required sections. See the [fedora project](https://fedoraproject.org/wiki/Packaging:Scriptlets).

**Comment by waveclaw** [comment]
Should be working in 0.11 per testing.
