### ISSUE TITLE
%include recognised as variable instead of macro

### ISSUE THREAD

**Issue by Keyhaku** [waveclaw/language-rpm-spec#12]
Hi,

The macro %include should be recognised as a valid macro not as a variable.

I know that this macro is not well documented, in official documentation you can find only one example here : [http://rpm.org/wiki/PackagerDocs/RpmLua#Includingscripts](url)
But in rpmlist you can find some people discussing about it.

See ya

**Comment by waveclaw** [comment]
`rpm --eval` on the platforms I tested (SLES, SuSE, RHEL, CentOS) do not respond to %include as a macro, just as a variable.
